PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DROP TABLE tbl_user;
CREATE TABLE tbl_user (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    jn VARCHAR(128) NOT NULL,
    cn VARCHAR(128) NOT NULL,
    title VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    intel VARCHAR(128) NOT NULL,
    profile VARCHAR(128) NOT NULL
);
COMMIT;
